### ISSUE TITLE
初始化数据库数据？

### ISSUE THREAD

**Issue by zyearn** [MorganZhang100/zhihu-spider#1]
你好。看了下 question.py 和 topic.py 的代码，这两个脚本基于mysql里已有的数据来做爬数据。但是调用init.sql只是初始化表，所以做好可以再写个 initdb.py，可以在配置文件里设置初始 topic 或者初始 question，Initdb.py读这个配置并插入数据库，对吧？

**Comment by MorganZhang100** [comment]
你说的对，是我忘记添加初始数据了，多谢你的提醒！~
我已经添加了一些初始数据到init.sql里，你试试看。
