### ISSUE TITLE
请问cookie具体指的哪个？

### ISSUE THREAD

**Issue by myWythe** [MorganZhang100/zhihu-spider#3]
在我的缓存里知乎对应的有很多，请问应该怎么选择？
![cookie](https://cloud.githubusercontent.com/assets/5146162/7670073/b374b4d2-fcc7-11e4-9cdc-bff086281ec3.png)

**Comment by kehao95** [comment]
**所有的**
以 ; 分隔，可以在network下找到headers看看请求zhihu.com时的cookie然后全部复制即可。

![image](https://cloud.githubusercontent.com/assets/6213976/8325825/eb7b2fe8-1a8e-11e5-903c-6fa5c3655b45.png)

util.py文件下也可以看到Header的拼接格式

``` python
cookie = cf.get("cookie", "cookie")
    headers = {
        'Cookie': cookie,
        'Host': 'www.zhihu.com',
        'Referer': 'http://www.zhihu.com/',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36',
        'Accept-Encoding': 'gzip'
    }
```

**Comment by MorganZhang100** [comment]
谢谢@kehao95
